(require "asdf")
(ql:quickload "split-sequence")
(ql:quickload "usocket")
(ql:quickload "cl-store")
(ql:quickload "alexandria")
(declaim #+sbcl(sb-ext:muffle-conditions style-warning))
(asdf:load-system :mushy)
(sb-thread:make-thread 'ticker :name "ticker")
(sb-thread:make-thread 'start-server :name "server")
(load-material (directory "data/materials/*.*"))
(make-test-world)