(require "asdf")
(ql:quickload '(split-sequence usocket cl-store alexandria cl-ppcre))
(declaim #+sbcl(sb-ext:muffle-conditions style-warning))
(declaim #+sbcl(sb-ext:muffle-conditions warning))
(setq *print-pretty* 'nil)
(proclaim '(optimize (speed 0) (safety 3) (debug 3) (space 0)))
(asdf:load-system :mushy)
(sb-thread:make-thread 'ticker :name "ticker")
(sb-thread:make-thread 'start-server :name "server")
(load-material (directory "data/materials/*.*"))
(make-test-world)